services:
  server:
    build: ./server
    env_file:
      - server/.env
    ports:
      # allow override of published port
      - "127.0.0.1:${EXTERNAL_PORT:-9000}:8000"
    volumes:
      - shl-server-data:/app/db

volumes:
  shl-server-data: {}
