# docker continuous delivery
# build docker images and push to configured repo, with tags to match branches and git tags
---
name: Build & Deliver
on: [push]
jobs:
  test:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:  
          deno-version: v1.25.2

      - name: Run Deno Tests
        run: TEST=1 deno test -A --quiet --parallel
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git commit
        uses: actions/checkout@main

      - name: Publish server images to GitHub Container Registry
        # TODO: pin to hash
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: ${{ github.repository }}-server
          registry: ghcr.io

          # GitHub actor
          username: ${{ github.actor }}

          # GitHub access token
          password: ${{ secrets.GITHUB_TOKEN }}

          # create docker image tags to match git tags
          tag_names: true

          # build Dockerfile in server/ service directory
          workdir: server
